[package]
name = "solana-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
borsh = "0.10.3"
solana-program = "1.16.18"

[lib]
crate-type = ["cdylib", "lib"]
